### ISSUE TITLE
getting error on new fields

### ISSUE THREAD

**Issue by MustafaBaltee** [ext/Magento-Api-Stub#1]
I have a custom table and i want to make api for that table data. i tried to change Api.php and wsdl.xml but its not working ...

**Comment by ext** [comment]
Yes, I'm sorry but I don't think I can be of any help. It's been a few years since I last touched Magento. I've used this template quite a few times and at the time it worked out-of-the-box but I would assume things have changed since then. Isn't Magento 1 close to end of life anyway?
